### ISSUE TITLE
How to increase the number of parameters

### ISSUE THREAD

**Issue by cutoken** [keyvank/femtoGPT#1]
Hi,
It's mentioned that this has 300k parameters. How to increase the number of parameters. Is it by increasing the number of layers/heads ?  (also how are the total  parameters calculated)

Thank you for attempting a pure Rust implementation of GPT. Helps a lot to understand things without having to understand python voodoo.

Edit: Also if possible having some comments around important parts of the code will help a lot from learning perspective. Would be great if you wrote a blog post on it :)

**Comment by keyvank** [comment]
@cutoken 

Hey! Yes you can increase params by:

- Adding more layers
- Increasing the embedding degree (Then you will also need to adjust head_size)

The original 10M parameter of Andrej Karpathy's video has:

Layers: 6
Embedding-degree: 384
Heads: 6
Num-tokens: 256

Sure, I will try to write a blog post about it. Maybe in the README of Github :)
