### ISSUE TITLE
Promotion: let's make a tutorial blog post or ...

### ISSUE THREAD

**Issue by keyvank** [keyvank/femtoGPT#12]
Maybe create a tutorial for training a GPT model on Rust and put it on codeproject.com? Or somewhere similar?

**Comment by cutoken** [comment]
May be medium/substack or some other normal blog sites is better. You can also serve it from this repo it self!  :)

**Comment by pcranaway** [comment]
should this issue be closed? you already made that :P

**Comment by keyvank** [comment]
Hah yeah, wasn't very successful though :d closing
