### ISSUE TITLE
Use Sine/Cosine patterns for positional encoding

### ISSUE THREAD

**Issue by keyvank** [keyvank/femtoGPT#16]
This will reduce our number of params and make our model faster.

Trade-off could be complexity in femtoGPT.

I can assign you @cutoken to this if you are interested.

**Comment by cutoken** [comment]
I'll try @keyvank I'll bother you with a lot of questions if I have doubts.

**Comment by keyvank** [comment]
@cutoken Np ready to answer your questions!

**Comment by keyvank** [comment]
@cutoken Look: https://arxiv.org/abs/1905.04226

**Comment by cutoken** [comment]
Interesting @keyvank . Give both with (new) and old (without) a try. I felt even though loss is same, the sentences seem to make more sense with positional encoding. Also the loss converges much faster with sentence piece with pos encoding than without (haven't tried without recently but when I tried last time it was stuck at 2.0 - which falls nicely below 2.0 with the latest changes).
